keras.preprocessing.image.ImageDataGenerator(
　　　　featurewise_center=False, #输入值按照均值为0进行处理
　　　　samplewise_center=False, #每个样本的均值按0处理
　　　　featurewise_std_normalization=False, #输入值按照标准正态化处理
　　　　samplewise_std_normalization=False, #每个样本按照标准正态化处理 
　　　　zca_whitening=False, # 是否开启增白
　　　　zca_epsilon=1e-06, 
　　　　rotation_range=0, #图像随机旋转一定角度，最大旋转角度为设定值
　　　　width_shift_range=0.0, #图像随机水平平移，最大平移值为设定值。若值为小于1的float值，则可认为是按比例平移，若大于1，则平移的是像素；若值为整型，平移的也是像素；假设像素为2.0，则移动范围为[-1,1]之间
　　　　height_shift_range=0.0, #图像随机垂直平移，同上
　　　　brightness_range=None, # 图像随机亮度增强，给定一个含两个float值的list，亮度值取自上下限值间
　　　　shear_range=0.0, # 图像随机修剪
　　　　zoom_range=0.0, # 图像随机变焦 
　　　　channel_shift_range=0.0, 
　　　　fill_mode='nearest', #填充模式，默认为最近原则，比如一张图片向右平移，那么最左侧部分会被临近的图案覆盖
　　　　cval=0.0, 
　　　　horizontal_flip=False, #图像随机水平翻转
　　　　vertical_flip=False, #图像随机垂直翻转
　　　　rescale=None, #缩放尺寸
　　　　preprocessing_function=None, 
　　　　data_format=None, 
　　　　validation_split=0.0, 
　　　　dtype=None)
